// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/types.dart';
import '../dart_types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SESSION_COUNTER`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<void> flutterRealtimePlayerInit({required PlatformInt64 ffiPtr}) =>
    RustLib.instance.api.crateApiSimpleFlutterRealtimePlayerInit(
      ffiPtr: ffiPtr,
    );

/// updates the counter and returns a session id
/// note that this doesn't create any resources apart from raising the counter
Future<PlatformInt64> createNewSession() =>
    RustLib.instance.api.crateApiSimpleCreateNewSession();

/// returns a session id that represents a playing session in rust
Stream<StreamState> createNewPlayable({
  required PlatformInt64 sessionId,
  required PlatformInt64 engineHandle,
  required VideoInfo videoInfo,
  Map<String, String>? ffmpegOptions,
}) => RustLib.instance.api.crateApiSimpleCreateNewPlayable(
  sessionId: sessionId,
  engineHandle: engineHandle,
  videoInfo: videoInfo,
  ffmpegOptions: ffmpegOptions,
);

/// marks the session as required by the ui
/// if the ui won't call this every 2 seconds
/// this session will terminate itself.
Future<void> markSessionAlive({required PlatformInt64 sessionId}) =>
    RustLib.instance.api.crateApiSimpleMarkSessionAlive(sessionId: sessionId);

Future<void> destroyEngineStreams({required PlatformInt64 engineId}) =>
    RustLib.instance.api.crateApiSimpleDestroyEngineStreams(engineId: engineId);

Future<void> destroyStreamSession({required PlatformInt64 sessionId}) => RustLib
    .instance
    .api
    .crateApiSimpleDestroyStreamSession(sessionId: sessionId);

Future<void> seekToTime({
  required PlatformInt64 sessionId,
  required double timeSeconds,
}) => RustLib.instance.api.crateApiSimpleSeekToTime(
  sessionId: sessionId,
  timeSeconds: timeSeconds,
);

Future<double> getCurrentTime({required PlatformInt64 sessionId}) =>
    RustLib.instance.api.crateApiSimpleGetCurrentTime(sessionId: sessionId);

Future<void> resizeStreamSession({
  required PlatformInt64 sessionId,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiSimpleResizeStreamSession(
  sessionId: sessionId,
  width: width,
  height: height,
);
