// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/types.dart';
import '../dart_types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SESSION_COUNTER`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<void> flutterRealtimePlayerInit({required PlatformInt64 ffiPtr}) =>
    RustLib.instance.api.crateApiSimpleFlutterRealtimePlayerInit(
      ffiPtr: ffiPtr,
    );

/// returns a texture id, this id is also used to identify the session
Stream<StreamState> createNewPlayable({
  required PlatformInt64 engineHandle,
  required VideoInfo videoInfo,
  Map<String, String>? ffmpegOptions,
}) => RustLib.instance.api.crateApiSimpleCreateNewPlayable(
  engineHandle: engineHandle,
  videoInfo: videoInfo,
  ffmpegOptions: ffmpegOptions,
);

/// marks the session as required by the ui
/// if the ui won't call this every 2 seconds
/// this session will terminate itself.
Future<void> markSessionAlive({required PlatformInt64 sessionId}) =>
    RustLib.instance.api.crateApiSimpleMarkSessionAlive(sessionId: sessionId);

Future<void> destroyEngineStreams({required PlatformInt64 engineId}) =>
    RustLib.instance.api.crateApiSimpleDestroyEngineStreams(engineId: engineId);

Future<void> destroyStreamSession({required PlatformInt64 sessionId}) => RustLib
    .instance
    .api
    .crateApiSimpleDestroyStreamSession(sessionId: sessionId);
