// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/types.dart';
import '../dart_types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SESSION_COUNTER`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<void> flutterRealtimePlayerInit({required PlatformInt64 ffiPtr}) =>
    RustLib.instance.api.crateApiSimpleFlutterRealtimePlayerInit(
      ffiPtr: ffiPtr,
    );

/// updates the counter and returns a session id
/// note that this doesn't create any resources apart from raising the counter
Future<PlatformInt64> createNewSession() =>
    RustLib.instance.api.crateApiSimpleCreateNewSession();

Stream<StreamState> createNewPlayable({
  required PlatformInt64 sessionId,
  required PlatformInt64 engineHandle,
  required VideoInfo videoInfo,
  Map<String, String>? ffmpegOptions,
}) => RustLib.instance.api.crateApiSimpleCreateNewPlayable(
  sessionId: sessionId,
  engineHandle: engineHandle,
  videoInfo: videoInfo,
  ffmpegOptions: ffmpegOptions,
);

Stream<StreamState> createWscRtpPlayable({
  required PlatformInt64 sessionId,
  required PlatformInt64 engineHandle,
  required WscRtpSessionConfig config,
}) => RustLib.instance.api.crateApiSimpleCreateWscRtpPlayable(
  sessionId: sessionId,
  engineHandle: engineHandle,
  config: config,
);

Future<void> seekToTimestamp({
  required PlatformInt64 sessionId,
  required PlatformInt64 ts,
}) => RustLib.instance.api.crateApiSimpleSeekToTimestamp(
  sessionId: sessionId,
  ts: ts,
);

Future<void> wscRtpGoLive({required PlatformInt64 sessionId}) =>
    RustLib.instance.api.crateApiSimpleWscRtpGoLive(sessionId: sessionId);

Future<void> setSpeed({
  required PlatformInt64 sessionId,
  required double speed,
}) => RustLib.instance.api.crateApiSimpleSetSpeed(
  sessionId: sessionId,
  speed: speed,
);

Stream<StreamEvent> registerToStreamEventsSink({
  required PlatformInt64 sessionId,
}) => RustLib.instance.api.crateApiSimpleRegisterToStreamEventsSink(
  sessionId: sessionId,
);

/// marks the session as required by the ui
/// if the ui won't call this every 2 seconds
/// this session will be terminate.
Future<void> markSessionAlive({required PlatformInt64 sessionId}) =>
    RustLib.instance.api.crateApiSimpleMarkSessionAlive(sessionId: sessionId);

Future<void> destroyEngineStreams({required PlatformInt64 engineId}) =>
    RustLib.instance.api.crateApiSimpleDestroyEngineStreams(engineId: engineId);

Future<void> destroyStreamSession({required PlatformInt64 sessionId}) => RustLib
    .instance
    .api
    .crateApiSimpleDestroyStreamSession(sessionId: sessionId);
