version: "3"

vars:
    DART_BIN: "fvm exec dart"
    FLUTTER_BIN: "fvm exec flutter"
    LOCAL_FLUTTER_BIN: "/home/dev/Desktop/oss/flutter/bin/flutter"
    LOCAL_ENGINE: "host_debug"
    LOCAL_ENGINE_SRC_PATH: "/home/dev/Desktop/oss/flutter/engine/src"

tasks:
    codegen:
        cmds:
            - rm -rf .dart_tool
            - "{{.FLUTTER_BIN}} clean"
            - cd ./example  && {{.FLUTTER_BIN}} clean
            - flutter_rust_bridge_codegen generate
    test:
        cmds:
            - "{{.FLUTTER_BIN}} test --fail-fast --reporter=compact --coverage"
    lint:
        cmds:
            - cargo fix --allow-dirty
            - cargo check
            - "{{.FLUTTER_BIN}} analyze --disable-analytics ./lib"
            - "{{.DART_BIN}} fix --apply"
    fmt:
        cmds:
            - cargo fmt
            - "{{.DART_BIN}} format ./lib ./example"
    build-example-rust:
        desc: Run the example with the local Flutter Rust shell engine.
        dir: example
        cmds:
            - "{{.LOCAL_FLUTTER_BIN}} build rust --release --local-engine={{.LOCAL_ENGINE}} --local-engine-host={{.LOCAL_ENGINE}} --local-engine-src-path={{.LOCAL_ENGINE_SRC_PATH}}"
