// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class VideoDimensions {
  final int width;
  final int height;

  const VideoDimensions({required this.width, required this.height});

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoDimensions &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}

class VideoInfo {
  final String uri;
  final VideoDimensions dimensions;
  final int? framerate;
  final bool mute;
  final bool autoRestart;

  const VideoInfo({
    required this.uri,
    required this.dimensions,
    this.framerate,
    required this.mute,
    required this.autoRestart,
  });

  @override
  int get hashCode =>
      uri.hashCode ^
      dimensions.hashCode ^
      framerate.hashCode ^
      mute.hashCode ^
      autoRestart.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoInfo &&
          runtimeType == other.runtimeType &&
          uri == other.uri &&
          dimensions == other.dimensions &&
          framerate == other.framerate &&
          mute == other.mute &&
          autoRestart == other.autoRestart;
}

class WscSdpEndpoint {
  final String baseUrl;
  final String sourceId;
  final int? clientPort;

  /// Skip UDP negotiation and use WebSocket for RTP delivery from the start.
  final bool forceWebsocketTransport;

  const WscSdpEndpoint({
    required this.baseUrl,
    required this.sourceId,
    this.clientPort,
    required this.forceWebsocketTransport,
  });

  @override
  int get hashCode =>
      baseUrl.hashCode ^
      sourceId.hashCode ^
      clientPort.hashCode ^
      forceWebsocketTransport.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WscSdpEndpoint &&
          runtimeType == other.runtimeType &&
          baseUrl == other.baseUrl &&
          sourceId == other.sourceId &&
          clientPort == other.clientPort &&
          forceWebsocketTransport == other.forceWebsocketTransport;
}
