// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class VideoInfo {
  final String uri;
  final int? framerate;
  final bool mute;
  final bool autoRestart;

  const VideoInfo({
    required this.uri,
    this.framerate,
    required this.mute,
    required this.autoRestart,
  });

  @override
  int get hashCode =>
      uri.hashCode ^ framerate.hashCode ^ mute.hashCode ^ autoRestart.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoInfo &&
          runtimeType == other.runtimeType &&
          uri == other.uri &&
          framerate == other.framerate &&
          mute == other.mute &&
          autoRestart == other.autoRestart;
}

class WscRtpSessionConfig {
  final String baseUrl;
  final String sourceId;
  final int? clientPort;

  /// Skip UDP negotiation and use WebSocket for RTP delivery from the start.
  final bool forceWebsocketTransport;
  final bool autoRestart;

  const WscRtpSessionConfig({
    required this.baseUrl,
    required this.sourceId,
    this.clientPort,
    required this.forceWebsocketTransport,
    required this.autoRestart,
  });

  @override
  int get hashCode =>
      baseUrl.hashCode ^
      sourceId.hashCode ^
      clientPort.hashCode ^
      forceWebsocketTransport.hashCode ^
      autoRestart.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WscRtpSessionConfig &&
          runtimeType == other.runtimeType &&
          baseUrl == other.baseUrl &&
          sourceId == other.sourceId &&
          clientPort == other.clientPort &&
          forceWebsocketTransport == other.forceWebsocketTransport &&
          autoRestart == other.autoRestart;
}
