// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

class PlaybinConfig {
  final String uri;
  final bool mute;

  const PlaybinConfig({required this.uri, required this.mute});

  @override
  int get hashCode => uri.hashCode ^ mute.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybinConfig &&
          runtimeType == other.runtimeType &&
          uri == other.uri &&
          mute == other.mute;
}

@freezed
sealed class VideoConfig with _$VideoConfig {
  const VideoConfig._();

  const factory VideoConfig.wscRtp(WscRtpSessionConfig field0) =
      VideoConfig_WscRtp;
  const factory VideoConfig.playbin(PlaybinConfig field0) = VideoConfig_Playbin;
}

class WscRtpSessionConfig {
  final String baseUrl;
  final String sourceId;
  final int? clientPort;

  /// Skip UDP negotiation and use WebSocket for RTP delivery from the start.
  final bool forceWebsocketTransport;
  final bool autoRestart;

  const WscRtpSessionConfig({
    required this.baseUrl,
    required this.sourceId,
    this.clientPort,
    required this.forceWebsocketTransport,
    required this.autoRestart,
  });

  @override
  int get hashCode =>
      baseUrl.hashCode ^
      sourceId.hashCode ^
      clientPort.hashCode ^
      forceWebsocketTransport.hashCode ^
      autoRestart.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WscRtpSessionConfig &&
          runtimeType == other.runtimeType &&
          baseUrl == other.baseUrl &&
          sourceId == other.sourceId &&
          clientPort == other.clientPort &&
          forceWebsocketTransport == other.forceWebsocketTransport &&
          autoRestart == other.autoRestart;
}
