// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'core/types.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'dart_types.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<StreamEvent> dco_decode_StreamSink_stream_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<StreamState> dco_decode_StreamSink_stream_state_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlaybinConfig dco_decode_box_autoadd_playbin_config(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  VideoConfig dco_decode_box_autoadd_video_config(dynamic raw);

  @protected
  WscRtpMode dco_decode_box_autoadd_wsc_rtp_mode(dynamic raw);

  @protected
  WscRtpSessionConfig dco_decode_box_autoadd_wsc_rtp_session_config(
    dynamic raw,
  );

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  PlaybinConfig dco_decode_playbin_config(dynamic raw);

  @protected
  StreamEvent dco_decode_stream_event(dynamic raw);

  @protected
  StreamState dco_decode_stream_state(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VideoConfig dco_decode_video_config(dynamic raw);

  @protected
  WscRtpMode dco_decode_wsc_rtp_mode(dynamic raw);

  @protected
  WscRtpSessionConfig dco_decode_wsc_rtp_session_config(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<StreamEvent> sse_decode_StreamSink_stream_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<StreamState> sse_decode_StreamSink_stream_state_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlaybinConfig sse_decode_box_autoadd_playbin_config(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  VideoConfig sse_decode_box_autoadd_video_config(SseDeserializer deserializer);

  @protected
  WscRtpMode sse_decode_box_autoadd_wsc_rtp_mode(SseDeserializer deserializer);

  @protected
  WscRtpSessionConfig sse_decode_box_autoadd_wsc_rtp_session_config(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  PlaybinConfig sse_decode_playbin_config(SseDeserializer deserializer);

  @protected
  StreamEvent sse_decode_stream_event(SseDeserializer deserializer);

  @protected
  StreamState sse_decode_stream_state(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VideoConfig sse_decode_video_config(SseDeserializer deserializer);

  @protected
  WscRtpMode sse_decode_wsc_rtp_mode(SseDeserializer deserializer);

  @protected
  WscRtpSessionConfig sse_decode_wsc_rtp_session_config(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_stream_event_Sse(
    RustStreamSink<StreamEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_stream_state_Sse(
    RustStreamSink<StreamState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_playbin_config(
    PlaybinConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_video_config(
    VideoConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wsc_rtp_mode(
    WscRtpMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wsc_rtp_session_config(
    WscRtpSessionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_playbin_config(PlaybinConfig self, SseSerializer serializer);

  @protected
  void sse_encode_stream_event(StreamEvent self, SseSerializer serializer);

  @protected
  void sse_encode_stream_state(StreamState self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_video_config(VideoConfig self, SseSerializer serializer);

  @protected
  void sse_encode_wsc_rtp_mode(WscRtpMode self, SseSerializer serializer);

  @protected
  void sse_encode_wsc_rtp_session_config(
    WscRtpSessionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
