// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'core/types.dart';
import 'dart:async';
import 'dart:convert';
import 'dart_types.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 907721271;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'flutter_realtime_player',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<PlatformInt64> crateApiSimpleCreateNewSession();

  Stream<StreamState> crateApiSimpleCreatePlayable({
    required PlatformInt64 sessionId,
    required PlatformInt64 engineHandle,
    required VideoConfig config,
  });

  Future<void> crateApiSimpleDestroyEngineStreams({
    required PlatformInt64 engineId,
  });

  Future<void> crateApiSimpleDestroyStreamSession({
    required PlatformInt64 sessionId,
  });

  Future<void> crateApiSimpleFlutterRealtimePlayerInit({
    required PlatformInt64 ffiPtr,
  });

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiSimpleMarkSessionAlive({
    required PlatformInt64 sessionId,
  });

  Stream<StreamEvent> crateApiSimpleRegisterToStreamEventsSink({
    required PlatformInt64 sessionId,
  });

  Future<void> crateApiSimpleSeekToTimestamp({
    required PlatformInt64 sessionId,
    required BigInt ts,
  });

  Future<void> crateApiSimpleSetSpeed({
    required PlatformInt64 sessionId,
    required double speed,
  });

  Future<void> crateApiSimpleWscRtpGoLive({required PlatformInt64 sessionId});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<PlatformInt64> crateApiSimpleCreateNewSession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCreateNewSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCreateNewSessionConstMeta =>
      const TaskConstMeta(debugName: "create_new_session", argNames: []);

  @override
  Stream<StreamState> crateApiSimpleCreatePlayable({
    required PlatformInt64 sessionId,
    required PlatformInt64 engineHandle,
    required VideoConfig config,
  }) {
    final sink = RustStreamSink<StreamState>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_i_64(sessionId, serializer);
            sse_encode_i_64(engineHandle, serializer);
            sse_encode_box_autoadd_video_config(config, serializer);
            sse_encode_StreamSink_stream_state_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 2,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSimpleCreatePlayableConstMeta,
          argValues: [sessionId, engineHandle, config, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleCreatePlayableConstMeta =>
      const TaskConstMeta(
        debugName: "create_playable",
        argNames: ["sessionId", "engineHandle", "config", "sink"],
      );

  @override
  Future<void> crateApiSimpleDestroyEngineStreams({
    required PlatformInt64 engineId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(engineId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleDestroyEngineStreamsConstMeta,
        argValues: [engineId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDestroyEngineStreamsConstMeta =>
      const TaskConstMeta(
        debugName: "destroy_engine_streams",
        argNames: ["engineId"],
      );

  @override
  Future<void> crateApiSimpleDestroyStreamSession({
    required PlatformInt64 sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleDestroyStreamSessionConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDestroyStreamSessionConstMeta =>
      const TaskConstMeta(
        debugName: "destroy_stream_session",
        argNames: ["sessionId"],
      );

  @override
  Future<void> crateApiSimpleFlutterRealtimePlayerInit({
    required PlatformInt64 ffiPtr,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(ffiPtr, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleFlutterRealtimePlayerInitConstMeta,
        argValues: [ffiPtr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleFlutterRealtimePlayerInitConstMeta =>
      const TaskConstMeta(
        debugName: "flutter_realtime_player_init",
        argNames: ["ffiPtr"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiSimpleMarkSessionAlive({
    required PlatformInt64 sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMarkSessionAliveConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMarkSessionAliveConstMeta =>
      const TaskConstMeta(
        debugName: "mark_session_alive",
        argNames: ["sessionId"],
      );

  @override
  Stream<StreamEvent> crateApiSimpleRegisterToStreamEventsSink({
    required PlatformInt64 sessionId,
  }) {
    final sink = RustStreamSink<StreamEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_i_64(sessionId, serializer);
            sse_encode_StreamSink_stream_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 8,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSimpleRegisterToStreamEventsSinkConstMeta,
          argValues: [sessionId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleRegisterToStreamEventsSinkConstMeta =>
      const TaskConstMeta(
        debugName: "register_to_stream_events_sink",
        argNames: ["sessionId", "sink"],
      );

  @override
  Future<void> crateApiSimpleSeekToTimestamp({
    required PlatformInt64 sessionId,
    required BigInt ts,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          sse_encode_u_64(ts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleSeekToTimestampConstMeta,
        argValues: [sessionId, ts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSeekToTimestampConstMeta =>
      const TaskConstMeta(
        debugName: "seek_to_timestamp",
        argNames: ["sessionId", "ts"],
      );

  @override
  Future<void> crateApiSimpleSetSpeed({
    required PlatformInt64 sessionId,
    required double speed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          sse_encode_f_64(speed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleSetSpeedConstMeta,
        argValues: [sessionId, speed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSetSpeedConstMeta => const TaskConstMeta(
    debugName: "set_speed",
    argNames: ["sessionId", "speed"],
  );

  @override
  Future<void> crateApiSimpleWscRtpGoLive({required PlatformInt64 sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleWscRtpGoLiveConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleWscRtpGoLiveConstMeta => const TaskConstMeta(
    debugName: "wsc_rtp_go_live",
    argNames: ["sessionId"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<StreamEvent> dco_decode_StreamSink_stream_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<StreamState> dco_decode_StreamSink_stream_state_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  VideoConfig dco_decode_box_autoadd_video_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_video_config(raw);
  }

  @protected
  WscRtpSessionConfig dco_decode_box_autoadd_wsc_rtp_session_config(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_wsc_rtp_session_config(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  StreamEvent dco_decode_stream_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return StreamEvent_Error(dco_decode_String(raw[1]));
      case 1:
        return StreamEvent_CurrentTime(dco_decode_i_64(raw[1]));
      case 2:
        return StreamEvent_OriginVideoSize(
          width: dco_decode_u_64(raw[1]),
          height: dco_decode_u_64(raw[2]),
        );
      case 3:
        return StreamEvent_WscRtpSessionMode(
          isLive: dco_decode_bool(raw[1]),
          currentTimeMs: dco_decode_i_64(raw[2]),
          speed: dco_decode_f_64(raw[3]),
        );
      case 4:
        return StreamEvent_WscRtpStreamState(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  StreamState dco_decode_stream_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return StreamState_Error(dco_decode_String(raw[1]));
      case 1:
        return StreamState_Loading();
      case 2:
        return StreamState_Playing(
          textureId: dco_decode_i_64(raw[1]),
          seekable: dco_decode_bool(raw[2]),
        );
      case 3:
        return StreamState_Stopped();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VideoConfig dco_decode_video_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return VideoConfig_WscRtp(
          dco_decode_box_autoadd_wsc_rtp_session_config(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  WscRtpSessionConfig dco_decode_wsc_rtp_session_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return WscRtpSessionConfig(
      baseUrl: dco_decode_String(arr[0]),
      sourceId: dco_decode_String(arr[1]),
      clientPort: dco_decode_opt_box_autoadd_u_16(arr[2]),
      forceWebsocketTransport: dco_decode_bool(arr[3]),
      autoRestart: dco_decode_bool(arr[4]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<StreamEvent> sse_decode_StreamSink_stream_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<StreamState> sse_decode_StreamSink_stream_state_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  VideoConfig sse_decode_box_autoadd_video_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_video_config(deserializer));
  }

  @protected
  WscRtpSessionConfig sse_decode_box_autoadd_wsc_rtp_session_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_wsc_rtp_session_config(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StreamEvent sse_decode_stream_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return StreamEvent_Error(var_field0);
      case 1:
        var var_field0 = sse_decode_i_64(deserializer);
        return StreamEvent_CurrentTime(var_field0);
      case 2:
        var var_width = sse_decode_u_64(deserializer);
        var var_height = sse_decode_u_64(deserializer);
        return StreamEvent_OriginVideoSize(
          width: var_width,
          height: var_height,
        );
      case 3:
        var var_isLive = sse_decode_bool(deserializer);
        var var_currentTimeMs = sse_decode_i_64(deserializer);
        var var_speed = sse_decode_f_64(deserializer);
        return StreamEvent_WscRtpSessionMode(
          isLive: var_isLive,
          currentTimeMs: var_currentTimeMs,
          speed: var_speed,
        );
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return StreamEvent_WscRtpStreamState(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  StreamState sse_decode_stream_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return StreamState_Error(var_field0);
      case 1:
        return StreamState_Loading();
      case 2:
        var var_textureId = sse_decode_i_64(deserializer);
        var var_seekable = sse_decode_bool(deserializer);
        return StreamState_Playing(
          textureId: var_textureId,
          seekable: var_seekable,
        );
      case 3:
        return StreamState_Stopped();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VideoConfig sse_decode_video_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_wsc_rtp_session_config(
          deserializer,
        );
        return VideoConfig_WscRtp(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  WscRtpSessionConfig sse_decode_wsc_rtp_session_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_baseUrl = sse_decode_String(deserializer);
    var var_sourceId = sse_decode_String(deserializer);
    var var_clientPort = sse_decode_opt_box_autoadd_u_16(deserializer);
    var var_forceWebsocketTransport = sse_decode_bool(deserializer);
    var var_autoRestart = sse_decode_bool(deserializer);
    return WscRtpSessionConfig(
      baseUrl: var_baseUrl,
      sourceId: var_sourceId,
      clientPort: var_clientPort,
      forceWebsocketTransport: var_forceWebsocketTransport,
      autoRestart: var_autoRestart,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_stream_event_Sse(
    RustStreamSink<StreamEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_stream_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_stream_state_Sse(
    RustStreamSink<StreamState> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_stream_state,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_video_config(
    VideoConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_video_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_wsc_rtp_session_config(
    WscRtpSessionConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_wsc_rtp_session_config(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_stream_event(StreamEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case StreamEvent_Error(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case StreamEvent_CurrentTime(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_i_64(field0, serializer);
      case StreamEvent_OriginVideoSize(
        width: final width,
        height: final height,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_u_64(width, serializer);
        sse_encode_u_64(height, serializer);
      case StreamEvent_WscRtpSessionMode(
        isLive: final isLive,
        currentTimeMs: final currentTimeMs,
        speed: final speed,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_bool(isLive, serializer);
        sse_encode_i_64(currentTimeMs, serializer);
        sse_encode_f_64(speed, serializer);
      case StreamEvent_WscRtpStreamState(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_stream_state(StreamState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case StreamState_Error(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case StreamState_Loading():
        sse_encode_i_32(1, serializer);
      case StreamState_Playing(
        textureId: final textureId,
        seekable: final seekable,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_i_64(textureId, serializer);
        sse_encode_bool(seekable, serializer);
      case StreamState_Stopped():
        sse_encode_i_32(3, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_video_config(VideoConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case VideoConfig_WscRtp(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_wsc_rtp_session_config(field0, serializer);
    }
  }

  @protected
  void sse_encode_wsc_rtp_session_config(
    WscRtpSessionConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.baseUrl, serializer);
    sse_encode_String(self.sourceId, serializer);
    sse_encode_opt_box_autoadd_u_16(self.clientPort, serializer);
    sse_encode_bool(self.forceWebsocketTransport, serializer);
    sse_encode_bool(self.autoRestart, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
