// Generated by Flutter. Do not edit.

use flutter_plugin_sdk::{PluginRegistrar, Result};

pub(crate) fn register_plugins(registrar: &mut PluginRegistrar) -> Result<()> {
    flutter_rs_plugin_flutter_realtime_player::register(registrar)?;
    Ok(())
}
