[package]
name = "flutter_realtime_player_example"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"
publish = false
build = "build.rs"

[lib]
path = "src/lib.rs"

[[bin]]
name = "flutter_realtime_player_example"
path = "src/main.rs"

[dependencies]
flutter-plugin-sdk = { path = "../.dart_tool/flutter_rs/sdk/crates/flutter-plugin-sdk" }
flutter-shell-winit = { path = "../.dart_tool/flutter_rs/sdk/crates/flutter-shell-winit" }

# === BEGIN FLUTTER GENERATED RUST PLUGINS ===
flutter_rs_plugin_flutter_realtime_player = { package = "flutter_realtime_player", path = "../.dart_tool/flutter_rs/plugins/flutter_realtime_player" }
# === END FLUTTER GENERATED RUST PLUGINS ===

[patch.crates-io]
flutter-plugin-sdk = { path = "../.dart_tool/flutter_rs/sdk/crates/flutter-plugin-sdk" }
winit-wayland = { path = "../.dart_tool/flutter_rs/sdk/third_party/winit-wayland" }

[profile.flutter-profile]
inherits = "release"
debug = true

[workspace]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(frb_expand)"] }
