// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<void> flutterGstreamerInit({required PlatformInt64 ffiPtr}) =>
    RustLib.instance.api.crateApiSimpleFlutterGstreamerInit(ffiPtr: ffiPtr);

Future<PlatformInt64> createNewPlayable(
        {required PlatformInt64 engineHandle, required VideoInfo videInfo}) =>
    RustLib.instance.api.crateApiSimpleCreateNewPlayable(
        engineHandle: engineHandle, videInfo: videInfo);
