// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `IS_INITIALIZED`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<void> flutterGstreamerInit({required PlatformInt64 ffiPtr}) =>
    RustLib.instance.api.crateApiSimpleFlutterGstreamerInit(ffiPtr: ffiPtr);

/// returns a texture id, this id is also used to identify the session
Future<PlatformInt64> createNewPlayable(
        {required PlatformInt64 engineHandle, required VideoInfo videInfo}) =>
    RustLib.instance.api.crateApiSimpleCreateNewPlayable(
        engineHandle: engineHandle, videInfo: videInfo);

Future<void> destroyPlayable({required PlatformInt64 textureId}) =>
    RustLib.instance.api.crateApiSimpleDestroyPlayable(textureId: textureId);
